### PR TITLE
prettier lint fix + bump version

### PR DESCRIPTION
**Pull request by YayC**
followup to https://github.com/temoncher/eslint-plugin-clsx/issues/7.

should we add a git precommit hook for `npm run lint`?

### CODE REVIEW

**Comment by YayC** [comment]
eh on second thought precommit hook would be annoying. I should have noticed the editor lint warnings

**Comment by temoncher** [comment]
> eh on second thought precommit hook would be annoying

Yes, I agree

I'm not really good at GitHub workflows, maybe you can add workflow to run lint command on every merge request to main branch?

**Comment by temoncher** [comment]
I thought the one in .github/workflows/main.yml should do the trick, but I don't see any checks on your PRs..

**Comment by YayC** [comment]
I think this should do it https://github.com/temoncher/eslint-plugin-clsx/pull/10

**Pull request merged**
